version: "3.8"
services:
  mywebsite:
    image: myapp:latest
    ports:
      - 3000:8080
    deploy:
      replicas: 3
  otherMyWebsite:
    image: myapp:latest
    ports:
      - 3001:8080
    deploy:
      replicas: 2